language: java
sudo: false
jdk: openjdk8
addons:
  apt:
    packages:
      - oracle-java8-installer

script: "mvn clean install cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 4be4064d-d269-4949-aff3-bb0307e04c7c