language: java
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.m2
script: "mvn clean install cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 4be4064d-d269-4949-aff3-bb0307e04c7c